WIP
Everything is OK here except:

1. Linux Swift 5.5 has a full proper SDK; Xcode 13 does not.
   So Linux is finding all the Sendable conformances.
   Just wait until a new Xcode 13.1 beta I guess.

2. SourceKitten needs a release and an updated dependency on arg-parser
   Currently it's not compatible with SwiftSyntax:

   error: Dependencies could not be resolved because root depends on 'swift-argument-parser' 0.4.0..<0.5.0.
'swift-argument-parser' >= 1.0.1 is required because 'swift-format' 0.50500.0 depends on 'swift-argument-parser' 1.0.1..<1.1.0 and root depends on 'swift-format' 0.50500.0.